name: helm-01
namespace: mauricio-toapanta-dev
container:
  tag: 20
  port: 3000
  image: "hola-mundo-clase-86"
  resources:
    requests:
      cpu: "500m"
      memory: "800Mi"
    limits:
      cpu: "1000m"
      memory: "1500Mi"
 
hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
configmap:
  database: "192.168.1.1"
secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"